name: Licensed

on:
  workflow_dispatch:
    inputs:
      remote-repo:
        description: "Set up your repository to checkout"
        required: true
        type: string
        default: ''
      remote-branch:
        description: "Remote branch to checkout"
        required: true
        type: string
        default: ''

jobs:
  cache-dependencies-records:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.remote-repo}}
          ref: ${{inputs.remote-branch}}

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install licensed tool
        run: |
          cd "$RUNNER_TEMP"
          curl -Lfs -o licensed.tar.gz https://github.com/github/licensed/releases/download/3.9.0/licensed-3.9.0-linux-x64.tar.gz 
          sudo tar -xzf licensed.tar.gz
          sudo mv licensed /usr/local/bin/licensed

      - run: licensed cache

      - uses: actions/upload-artifact@v3
        with:
          name: licensed-artifact
          path: .licenses

      - name: Check cached dependency records
        run: licensed status