name: Setup-java
on:
  workflow_dispatch:
  

jobs:
  test-ip-ubuntu:
    runs-on: ${{ matrix.os }}
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.5
#     - run: echo $pythonLocation        
    - run: python --version

#   issue_candidate:
#     runs-on: ubuntu-20.04

#     container:
#       image: ${{ matrix.os }}

#     strategy:
#       fail-fast: false

#       matrix:
#         os:
#           - 'centos:7'
#         python:
#           - '3.6'
#           - '3.7'
#           - '3.8'
#           - '3.9'
#           - '3.10'
#     steps:
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python }}

#       - name: Check that Python is ok
#         run: python --version

#   build-linux:
#     # Build Linux binaries, ready for release.
#     # This runs inside an Alpine Linux container so we can more easily create a
#     # statically linked binary.
#     runs-on: ubuntu-latest
#     container:
#       image: alpine:3.16
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - run: apk add tar git openssh gcompat make g++ ruby
#       - name: Install Go
#         uses: dmitry-shibanov/setup-go@v-dmshib/test-command-output
#         with:
#           go-version: '1.18'
#       - run: go env GOMODCACHE
          
#   setup-node-check-latest:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [windows-latest, ubuntu-latest]
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3
#     - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
#       with:
#         node-version: 20.0.0-nightly202211061f517130dd
#     - run: node --version
#     - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
#       with:
#         node-version: 20-nightly
#         check-latest: true
#     - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
#       with:
#         node-version: 16-nightly
#     - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
#       with:
#         node-version: 16
#     - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
#       with:
#         node-version: 16
#         check-latest: true
#     - run: node --version
#   test-setup-python:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [windows-latest, ubuntu-latest]
#         version: [17-nightly, 18-nightly, 16.0.0-nightly, 19.0.0-nightly202204201fe5d56403, 17.0.0-rc.1, 17.0.0-rc.2]
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3
#     - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
#       with:
#         node-version: ${{ matrix.version }}
#     - run: node --version
#     - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
#       with:
#         node-version: ${{ matrix.version }}
#     - run: node --version
