name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
#       - run: |
#           majorVersion=$(node -v | cut -d. -f1 | cut -d'v' -f2)
#           npm -v
#           npm i -g npm@7 --prefix=/usr/local/opt/node@$majorVersion
#           npm -v
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.0-rc1'
      - name: Setup NODE
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - run: |
          echo -e "let myVar;\n console.log(12);" >> check.js
          node check.js
      - run: yarn --prefer-offline



  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint

  pythonInContainer:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - run: python --version
