name: Setup-java
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
#       - name: remove dir
#         shell: pwsh
#         if: ${{ runner.os == 'Windows' }}
#         run: |
#           $pythonToolcachePath = Join-Path -Path "C:\hostedtoolcache\windows" -ChildPath "Python"
#           $pythonVersion = Join-Path -Path $pythonToolcachePath -ChildPath ${{ matrix.python-version }}
#           if (Test-Path -Path $pythonVersion) {
#             Remove-Item -Path $pythonVersion -Recurse -Force
#           }

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm config get cache
          node -e "const exec = require('child_process'); const fs = require('fs'); const output = exec.execSync('yarn cache dir').toString().trim(); console.log(output); console.log(fs.existsSync(output));"
    
  
      - name: Check yarn directory
        shell: bash
        run: |
          checkDir=$(yarn cache dir)
          echo $checkDir
          [[ -d $checkDir ]] && echo "This directory exists!"
          
      - uses: dmitry-shibanov/setup-python@change-branch-to-update-versions-manifest-file
        with:
          python-version: 3.8.11
          
      - name: Check python version 
        run: python --version
        
