name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup NODE
        uses: actions/setup-node@v2
#         with:
#           node-version: 14

      - uses: Xlient/setup-dotnet@support-multiple-versions
        with:
          dotnet-version: |
            3.1.x
            5.0
#       - uses: actions/setup-java@v2
#         with:
#           distribution: temurin
#           java-version: 17
#       - run: java -version
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 16
#       - name: Install Firebase Tools
#         run: |
#           yarn global add firebase-tools
#           echo "$(yarn global bin)" >> $GITHUB_PATH
#       - name: Use Firebase Tools
#         run: |
#           firebase --version

#       - run: npm i -g @lhci/cli@0.4.x
#       - uses: actions/setup-go@v2
#         with:
#           stable: 'false'
#           go-version: '1.14.0-rc1'
#       - run: |
#           go version
#           node --version
#           npm --version
      - run: |
          node --version
          npm --version
          sudo npm install -g npm@latest
          npm --version
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.10.0-rc.1
