name: Setup-java
on:
  workflow_dispatch:
  

jobs:
#   test-ip-ubuntu:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [macos-11]
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 18
#         check-latest: true
#     - run: node --version



#   build-linux:
#     # Build Linux binaries, ready for release.
#     # This runs inside an Alpine Linux container so we can more easily create a
#     # statically linked binary.
#     runs-on: ubuntu-latest
#     container:
#       image: alpine:3.16
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - run: apk add tar git openssh gcompat make g++ ruby
#       - name: Install Go
#         uses: dmitry-shibanov/setup-go@v-dmshib/test-command-output
#         with:
#           go-version: '1.18'
#       - run: go env GOMODCACHE
          
  setup-node-check-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
      with:
        node-version: 20.0.0-nightly20221024aab9f3246e
    - run: node --version
    - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
      with:
        node-version: 20-nightly
        check-latest: true
    - run: node --version
  test-setup-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        version: [17-nightly, 18-nightly, 16.0.0-nightly, 19.0.0-nightly202204201fe5d56403, 17.0.0-rc.1, 17.0.0-rc.2]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
      with:
        node-version: ${{ matrix.version }}
    - run: node --version
    - uses: dmitry-shibanov/setup-node@v-dmshib/add-support-for-nightly-and-rc
      with:
        node-version: ${{ matrix.version }}
    - run: node --version
