name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12
      
      - run: |
          node --version
          npm --version
          npm ci
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: package-lock.json
          path: package-lock.json
