name: Setup-java
on:
  workflow_dispatch:

jobs:
  test-ip-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - run: |
        env | grep "JAVA_HOME"
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - run: |
        env | grep "JAVA_HOME"
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - run: |
        env | grep "JAVA_HOME"
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: |
        env | grep "JAVA_HOME"
    
