name: Setup-java
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
#       - name: remove dir
#         shell: pwsh
#         if: ${{ runner.os == 'Windows' }}
#         run: |
#           $pythonToolcachePath = Join-Path -Path "C:\hostedtoolcache\windows" -ChildPath "Python"
#           $pythonVersion = Join-Path -Path $pythonToolcachePath -ChildPath ${{ matrix.python-version }}
#           if (Test-Path -Path $pythonVersion) {
#             Remove-Item -Path $pythonVersion -Recurse -Force
#           }
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
          check-latest: true
      - name: Display Java version
        run: java -version
