name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
#       - run: |
#           yarn init --yes
#           yarn add express body-parser nodemon mongoose
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - run: |
          npm config get cache
          node -e "const exec = require('child_process'); const fs = require('fs'); const output = exec.execSync('yarn cache dir').toString().trim(); console.log(output); console.log(fs.existsSync(output));"
          yarn audit

      - uses: actions/upload-artifact@v2
        with:
          name: yarn.lock
          path: yarn.lock
