name: Setup-java
on:
  workflow_dispatch:
  

jobs:
#   test-ip-ubuntu:
#     runs-on: ${{ matrix.os }}
#     env:
#       PIP_DISABLE_PIP_VERSION_CHECK: 1
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest]
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#       - name: Setup Node 18
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - run: node --version
# #     - name: Checkout repository
# #       uses: actions/checkout@v3
#     - run: git clone https://github.com/tox-dev/tox.git .
#     - uses: dmitry-shibanov/setup-python@v-dmshib/install-multiple-python-versions
#       with:
#         python-version: |
#               3.10
#               3.9
#               3.8
#               3.7
#               3.6
# #     - run: echo $pythonLocation        
#     - run: python --version
#     - run: pip install tox
#     - run: tox -e py27,py36,py37,py38,py39,py310 -p all

#   issue_candidate:
#     runs-on: ubuntu-20.04

#     container:
#       image: ${{ matrix.os }}

#     strategy:
#       fail-fast: false

#       matrix:
#         os:
#           - 'centos:7'
#         python:
#           - '3.6'
#           - '3.7'
#           - '3.8'
#           - '3.9'
#           - '3.10'
#     steps:
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python }}

#       - name: Check that Python is ok
#         run: python --version

#   build-linux:
#     # Build Linux binaries, ready for release.
#     # This runs inside an Alpine Linux container so we can more easily create a
#     # statically linked binary.
#     runs-on: ubuntu-latest
#     container:
#       image: alpine:3.16
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - run: apk add tar git openssh gcompat make g++ ruby
#       - name: Install Go
#         uses: dmitry-shibanov/setup-go@v-dmshib/test-command-output
#         with:
#           go-version: '1.18'
#       - run: go env GOMODCACHE
          
  setup-node-check-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: actions/setup-node@main
      with:
        node-version: 20.0.0-nightly202211061f517130dd
    - run: node --version
    - uses: actions/setup-node@main
      with:
        node-version: 20-nightly
        check-latest: true
    - run: node --version
    - uses: actions/setup-node@main
      with:
        node-version: 16-nightly
    - run: node --version
    - uses: actions/setup-node@main
      with:
        node-version: 16
    - run: node --version
    - uses: actions/setup-node@main
      with:
        node-version: 16
        check-latest: true
    - run: node --version
    - uses: actions/setup-node@main
      with:
        node-version: 20.0.0-v8-canary20221103f7e2421e91
    - run: node --version
    - uses: actions/setup-node@main
      with:
        node-version: 20.0.0-v8-canary
        check-latest: true
    - run: node --version
  test-setup-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        version: [~16.4.0]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: akv-platform/setup-node@v-sdolin/v8-canary
      with:
        node-version: ${{ matrix.version }}
    - run: node --version
    - uses: akv-platform/setup-node@v-sdolin/v8-canary
      with:
        node-version: ${{ matrix.version }}
    - run: node --version
