name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
#       - run: |
#           majorVersion=$(node -v | cut -d. -f1 | cut -d'v' -f2)
#           npm -v
#           npm i -g npm@7 --prefix=/usr/local/opt/node@$majorVersion
#           npm -v
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.0-rc1'
      - name: Setup NODE
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - run: yarn --prefer-offline



  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.PAT_CHECKOUT }}
#           submodules: true
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@testacc-art"
          always-auth: true
      - name: fetch
        run: yarn add @testacc-art/testrepo@1.0.2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TOKEN}}
