name: Setup-java
on:
  workflow_dispatch:
  
jobs:
  test-ip-ubuntu:
    runs-on: ${{ matrix.os }}
    # defaults:
    #   run:
    #     shell: bash -el {0}
#     env:
#       PIP_DISABLE_PIP_VERSION_CHECK: 1
#       PIP_NO_PYTHON_VERSION_WARNING: 1
#       PIP_ROOT_USER_ACTION: ignore
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        # version: ["==3.10.10", "==3.10"]
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get remove -y python3

          wget https://github.com/pyston/pyston/releases/download/pyston_2.3.5/pyston_2.3.5_20.04_amd64.deb
          ls
          currentPath=$(pwd)
          echo "currentPath is $currentPath"
          sudo apt install $currentPath/pyston_2.3.5_20.04_amd64.deb
          ls /usr/lib/
          python3 --version
          # which python
          
      - run: |
          # python --version
          ls /usr/bin
          which python3
          echo -e "import sys\nhasattr(sys, "pyston_version_info")" | python3
      # - run: |
      #     ls -lA /usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
      #     node -e "const fs = require('fs');console.log(fs.realpathSync('/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages'))"
      #     which python
      #     pkgutil --pkgs
      #     sudo pkgutil --forget org.python.Python.PythonFramework-2.7
      #     ls -la /Users/runner/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages
      #     brew ls python@3.11
      #     brew uninstall --ignore-dependencies python@3.11
      #     ls -la /Users/runner/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages
      #     echo $PATH
      #     pip show pip
      #     pip install pip==23.0
      #     pip show pip
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          # cache-dependency-path: package.json
      - run: node --version
      - run: npm install express
      
      # - uses: actions/setup-go@v4
      #   with:
      #     go-version: '~1.21.0-0'
      # - run: go version
      # - run: |
      #     # find /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages -name 'pip-*.dist-info'
      #     ls -lA /Users/runner/hostedtoolcache/Python/3.11.4
      #     ls -lA /Users/runner/hostedtoolcache/Python/3.11.4/x64
      #     ls -lA /Users/runner/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages
      #     echo "--------------"
      #     ls -lA /Users/runner/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages
      #     which pip
      #     pip3 show pip
      #     pip3 install --ignore-installed pip==23.0
      #     pip3 show pip
      # - run: |
      #     sudo apt-get update
      #     sudo apt-get install -y --allow-downgrades python3-tk
# #     - run: rm -rf /opt/hostedtoolcache/PyPy/*
#       - run: echo $PATH
#       - run: ls /usr/local/bin
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         id: cpy
#         with:
#           python-version: ${{ matrix.version }}
#       - run: echo '${{ steps.cpy.outputs.python-path }}'
#       - run: ${{ steps.cpy.outputs.python-path }} --version
# #     - run: pip install numpy
#       - run: python --version
#       - run: /usr/local/bin/python --version
#       - run: ls /usr/local/bin
#       - run: which python
#       - run: echo $PATH
#       - name: Checkout
#         uses: actions/checkout@v3
# #         with:
# #           repository: pytorch/TensorRT
# #           ref: main
    
    
# #       - run: echo $env:PATH
# #         shell: pwsh
# #       - name: Download python 2.7
# #         run: |
# #           wget https://github.com/actions/python-versions/releases/download/3.10.12-5200619051/python-3.10.12-linux-20.04-x64.tar.gz -O ${{ runner.temp }}/python-3.10.12-linux-20.04-x64.tar.gz
# #           echo "temporary directory"
# #           ls ${{ runner.temp }}
# #           echo "unpack tar.gz"
# #           mkdir ${{ runner.temp }}/python-3.10.12-linux-20.04-x64
# #           tar -xzvf ${{ runner.temp }}/python-3.10.12-linux-20.04-x64.tar.gz -C ${{ runner.temp }}/python-3.10.12-linux-20.04-x64
# #           echo "temporary directory"
# #           ls ${{ runner.temp }}
#       - run: echo ${{ runner.temp }}
#       - run: node -e "const os = require('os');console.log(os.tmpdir())"
#       - run: node -e "console.log(process.env.RUNNER_TEMP)"
# #       - name: Setup NodeJS
# #         uses: actions/setup-node@v3
# #         with:
# #           node-version: 18
# #           architecture: arm64
# #       - run: pip install pandas
# #       - run: python -m pip install --upgrade pip==22.3.1
# #       - run: python3 -m pip debug
#       - name: Run script
#         run: |
#           echo "run script"
#           bash setup.sh
#         working-directory: ${{ runner.temp }}/python-3.10.12-linux-20.04-x64
#       - run: echo "/opt/hostedtoolcache/Python/3.10.12/x64/" >> $GITHUB_PATH
#       - run: python --version



  test-setup-python-pipenv:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3 # louislam/setup-node@fix-armv7-cache 
      with:
        go-version: 1.21.0-rc.3
    - run: go version
#     - name: Setup Python
#       uses: actions/setup-python@v4 # louislam/setup-node@fix-armv7-cache 
#       with:
#         python-version: 3.7
        
#     - run: python --version
#     - run: pip --version
#     - run: pip cache dir
#     - run: sudo pip --version
#     - run: sudo pip cache dir
#     - run: sudo pip install numpy --no-binary :all
#     - run: sudo ls $(sudo pip cache dir)
#     - run: sudo ls /home/runner/.cache/pip
#     - run: pip cache dir
#     - run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
#     - run: pipenv install flake8==6.0.0 numpy==1.25.1 # --python 3.9
#     - run: ls
#     - run: cat Pipfile
#     - run: cat Pipfile.lock


#   test-setup-node-v3:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [ubuntu-20.04, ubuntu-22.04]
#         architecture: [arm, armv7l]
#     steps:
#     - name: Setup Node.js
#       uses: actions/setup-node@v3 # louislam/setup-node@fix-armv7-cache 
#       id: setup-node
#       with:
#         node-version: 16
#         architecture: ${{ matrix.architecture }}
        
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 16
#         architecture: ${{ matrix.architecture }}



  setup-go-v3:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        architecture: [x64, ppc, ppc64, ppc64le]
    steps:
    - name: Setup Go
      uses: adilhusain-s/setup-go@linux-ppc64le # actions/setup-go@v3
      with:
        go-version: '1.20'
        architecture: ${{ matrix.architecture }}
        
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 12
#         architecture: ${{ matrix.architecture }}      
      
