name: Setup-java
on: [push]

jobs:
  build:
    name: Setup-java ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
#         distribution: ['adopt-hotspot', 'adopt-openj9']
#         version: [11, 12, 13, 14, 8.0, 9.0]
    steps:
#       - uses: actions/checkout@v2
        
#       - uses: actions/setup-java@v2
#         with:
#           java-version: ${{ matrix.version }}
#           distribution: ${{ matrix.distribution }}
#           architecture: 'x86'

#       - name: Java -version
#         run: java -version
        
#       - uses: actions/setup-java@v2
#         with:
#           java-version: ${{ matrix.version }}
#           distribution: ${{ matrix.distribution }}
#           architecture: 'x32'

#       - name: Java -version
#         run: java -version
      - run: |
          node --version
          yarn --version
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - run: |
          node --version
          yarn --version
