name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: 12
      
      - name: Test
        uses: borales/actions-yarn@master
        with:
          cmd: 'node -v'

      - name: Test
        uses: borales/actions-yarn@master
        with:
          cmd: 'install'
#       - name: 'Upload Artifact'
#         uses: actions/upload-artifact@v2
#         with:
#           name: package-lock.json
#           path: package-lock.json

#   test:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os:
#           - ubuntu-latest
#           - macos-latest
#           - windows-latest
#         node_version:
#           - 12
#           - 14
#           - 16
#         architecture:
#           - x64
#         # an extra windows-x86 run:
#         include:
#           - os: windows-2016
#             node_version: 12
#             architecture: x86
#     name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup node
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node_version }}
#           architecture: ${{ matrix.architecture }}
#       - run: npm install

  test-alpine:
    runs-on: ubuntu-18.04
    container:
#       image: node:lts-alpine
      image: php:7.3-fpm-alpine

    steps:
    - uses: actions/checkout@v2
#     - run: node --version
    - run: |
        alpineArch="$(apk --print-arch)"
        echo "$alpineArch"
    - name: use Node
      uses: dmitry-shibanov/setup-node@v-dmshib/npm-version
      with:
        node-version: 17.1.0

    - run: apk add --no-cache libstdc++
#         architecture: arm64
#     - run: |
#         echo $PATH
#         ls /__t/node/12.22.7/x64/bin
#         ln -s /__t/node/12.22.7/x64/bin/node /usr/bin/node
#         apk --no-cache add ca-certificates wget
#         wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
#         wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk
#         apk add glibc-2.28-r0.apk
    - name: npm install
      run: npm install
