name: Setup-java
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, windows-2022]
    steps:
      - uses: actions/checkout@v2
#       - name: remove dir
#         shell: pwsh
#         if: ${{ runner.os == 'Windows' }}
#         run: |
#           $pythonToolcachePath = Join-Path -Path "C:\hostedtoolcache\windows" -ChildPath "Python"
#           $pythonVersion = Join-Path -Path $pythonToolcachePath -ChildPath ${{ matrix.python-version }}
#           if (Test-Path -Path $pythonVersion) {
#             Remove-Item -Path $pythonVersion -Recurse -Force
#           }

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm config get cache
          node -e "const exec = require('child_process'); const fs = require('fs'); const output = exec.execSync('npm config get cache').toString().trim(); console.log(output); console.log(fs.existsSync(output));"
      
      - name: Set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 8.0.292+10
          distribution: adopt-openj9
          
      - run: |
          ls C:\hostedtoolcache\windows\Java_Adopt-OpenJ9_jdk\8.0.292-10\x64\jre
          ls C:\hostedtoolcache\windows\Java_Adopt-OpenJ9_jdk\8.0.292-10\x64\bin
