name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
    steps:
#       - run: |
#           majorVersion=$(node -v | cut -d. -f1 | cut -d'v' -f2)
#           npm -v
#           npm i -g npm@7 --prefix=/usr/local/opt/node@$majorVersion
#           npm -v
      - uses: actions/checkout@v2

      - name: Setup-java
        uses: dmitry-shibanov/setup-java@v-dmshib/add-docs-microsoft
        with:
          distribution: microsoft
          java-version: 11
          java-package: jre
          
      - run: java -version
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.0-rc1'
      - name: Setup NODE
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - run: |
          echo -e "let myVar;\n console.log(12);" >> check.js
          node check.js
      - run: yarn --prefer-offline



  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13.2

  pythonInContainer:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - run: python --version
