name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - run: java -version
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          yarn --version
          yarn global add  serverless
          serverless -v
      - run: serverless -v
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
      - run: npm i -g @lhci/cli@0.4.x
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.0-rc1'
      - run: |
          go version
          node --version
          npm --version
      - run: |
          node -e "const os = require('os'); process.stdout.write('[warning]some error' + os.EOL)"
          node -e "const os = require('os'); process.stdout.write('::warning::some error' + os.EOL)"
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.10.0-rc.1
