name: Setup-java
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup NODE
        uses: actions/setup-node@v2
        with:
          node-version: "lts/gallium"
          cache: yarn
#       - run: echo 'NODE_OPTIONS="--openssl-legacy-provider"' >> $GITHUB_ENV
      - run: |
          cacheDir=$(yarn cache dir)
          echo "cacheDir is $cacheDir"
          rm -rf $cacheDir
#       - uses: actions/setup-java@v2
#         with:
#           distribution: temurin
#           java-version: 17
#       - run: java -version
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 16
#       - name: Install Firebase Tools
#         run: |
#           yarn global add firebase-tools
#           echo "$(yarn global bin)" >> $GITHUB_PATH
#       - name: Use Firebase Tools
#         run: |
#           firebase --version

#       - run: npm i -g @lhci/cli@0.4.x
#       - uses: actions/setup-go@v2
#         with:
#           stable: 'false'
#           go-version: '1.14.0-rc1'
#       - run: |
#           go version
#           node --version
#           npm --version
      - run: |
          node --version
          node -e "const os = require('os'); process.stdout.write('[warning]some error' + os.EOL)"
          node -e "const os = require('os'); process.stdout.write('::warning::some error' + os.EOL)"
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.10.0-rc.1
