name: Setup-java
on: [push]

jobs:
  build:
    name: Setup-java ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        distribution: ['adopt-hotspot', 'zulu', 'adopt-openj9']
        version: [11, 12, 13, 14, 8.0 9.0]
    steps:
      - uses: actions/checkout@v2

      - uses: MarcelCoding/setup-java@main
        with:
          java-version: ${{ matrix.version }}
          distribution: ${{ matrix.distribution }}
          architecture: 'x64'

      - name: Java -version
        run: java -version
